plugins {
    id "com.android.application"
}

android {
    namespace "com.bwa3d.homehublegacy"
    compileSdk 36

    defaultConfig {
        applicationId "com.bwa3d.homehublegacy"
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName "0.1.0-alpha1"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
